# 6.	Consider a Kaggle Competition called Digit Recognizer under the following link:
https://www.kaggle.com/c/digit-recognizer 

This is a Supervised ML Problem. You need to apply PCA, find the optimal features count and apply ML. (Algorithm Selection depends on you).

Note - We have already worked on this dataset while applying clustering in classroom. Its time to apply PCA and find out what we get when we submit the result on Kaggle. 
-	7 marks

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
from sklearn.cluster import KMeans

In [2]:
mnist_train=pd.read_csv('train_MNIST.csv')
mnist_train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
mnist_test=pd.read_csv('test_MNIST.csv')
mnist_test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
mnist_train.shape

(42000, 785)

In [5]:
mnist_train.describe().transpose().head(10)

          count      mean      std  min  25%  50%  75%  max
label   42000.0  4.456643  2.88773  0.0  2.0  4.0  7.0  9.0
pixel0  42000.0  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0
pixel1  42000.0  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0
pixel2  42000.0  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0
pixel3  42000.0  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0
pixel4  42000.0  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0
pixel5  42000.0  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0
pixel6  42000.0  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0
pixel7  42000.0  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0
pixel8  42000.0  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0

In [6]:
#mnist_train.isnull().sum().sort_values(ascending=False).head(20)
#sns.heatmap(mnist_train.isnull())

# Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [8]:
x=mnist_train.drop('label',axis=1)
y=mnist_train[['label']]

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x1=sc.fit_transform(x)
y1=sc.fit_transform(y)
x1=pd.DataFrame(x1,columns=x.columns)
x1.head()

C:\Users\HII\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\HII\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\HII\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\HII\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.034737,-0.02527,-0.018026,-0.011473,-0.009099,-0.006897,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.034737,-0.02527,-0.018026,-0.011473,-0.009099,-0.006897,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.034737,-0.02527,-0.018026,-0.011473,-0.009099,-0.006897,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.034737,-0.02527,-0.018026,-0.011473,-0.009099,-0.006897,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.034737,-0.02527,-0.018026,-0.011473,-0.009099,-0.006897,0.0,0.0,0.0,0.0

In [12]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=123)

In [ ]:
lg_mod=LogisticRegression()
lg_mod.fit(xtrain,ytrain)

C:\Users\HII\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\HII\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HII\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [ ]:
pred=lg_mod.predict(xtest)

In [ ]:
lr_r=accuracy_score(ytest,pred)*100
print("Accurary score using Logistic regression:",(lr_r*100))

In [ ]:
pd.crosstab(ytest,pred)

In [ ]:
from sklearn.decomposition import PCA
pc=PCA(n_components=120)
x2=pc.fit_transform(x)
x2=pd.DataFrame(x2)
x2.shape

In [ ]:
exvar=pc.explained_variance_ratio_*100
exvar[0:120].sum()

In [ ]:
pc.get_covariance()

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x2,y,test_size=0.3,random_state=0)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
DT_model=DecisionTreeClassifier()
DT_model.fit(x_train,y_train)
pred1=DT_model.predict(x_test)
Rf_model=RandomForestClassifier()
Rf_model.fit(x_train,y_train)
pred2=Rf_model.predict(x_test)
Lr_model=LogisticRegression()
Lr_model.fit(x_train,y_train)
pred4=Lr_model.predict(x_test)
Kn_model=KNeighborsClassifier()
Kn_model.fit(x_train,y_train)
pred5=Kn_model.predict(x_test)

In [ ]:
# kfold cross validation
from sklearn import model_selection
mod=[]
mod.append(('Decision Tree',DT_model))
mod.append(('Random Forest',Rf_model))
#mod.append(('Naive Bayes',Nb_model))
mod.append(('Linear Regression',Lr_model))
mod.append(('KNN',Kn_model))
result=[]
names=[]
#scoring='accuracy'
for name,model in mod:
    kfold=model_selection.KFold(n_splits=7,shuffle=True)# 5 fold cross validation function
    cv_results=model_selection.cross_val_score(model,x,y,cv=kfold,scoring='accuracy')
    result.append(cv_results)
    names.append(name)
    msg="%s:  Performance Range is  (%1.3f %s %1.3f) with a Varience error of (%f) and mean of %1.3f"%(name,cv_results.min()*100,'-',cv_results.max()*100,cv_results.std(),cv_results.mean()*100)
    print(msg)
# boxplot for the models

fig=plt.figure(figsize=[10,8])
fig.suptitle("Algorithm Comparison")
ax=fig.add_subplot(111)
plt.boxplot(result)
ax.set_xticklabels(names)
plt.show()

In [ ]:
from sklearn.decomposition import PCA
pc=PCA(n_components=120)
x2=pc.fit_transform(mnist_test)
test_x=pd.DataFrame(x2)
test_x.shape

In [ ]:
exvar=pc.explained_variance_ratio_*100
exvar[0:120].sum()

In [ ]:
pc.get_covariance()

In [ ]:
DT_model=DecisionTreeClassifier()
DT_model.fit(x_train,y_train)
pred1=DT_model.predict(test_x)
Rf_model=RandomForestClassifier()
Rf_model.fit(x_train,y_train)
pred2=Rf_model.predict(test_x)
Lr_model=LogisticRegression()
Lr_model.fit(x_train,y_train)
pred4=Lr_model.predict(test_x)
Kn_model=KNeighborsClassifier()
Kn_model.fit(x_train,y_train)
pred5=Kn_model.predict(test_x)

In [ ]:
final=np.array(np.ravel(pred2))
print(final.shape)
ID=np.array(range(1,test_x.shape[0]))
new=pd.DataFrame({'ImageId':ID,'Label':final})
new.head()

In [ ]:
new.to_csv('MNIST_Pred.csv',index=False)